### ISSUE TITLE
Support Resolving All Bits from Registry When query Is Absent in `blocks`

### ISSUE THREAD

**Issue by bluephlavio** [bluephlavio/bits-python#34]
### Issue Description

When querying for bits in a `blocks` field, the `query` field for each entry in the list could also be absent. In this case, the block should resolve to include **all bits** from the specified registry.

This behavior should apply to all contexts where `blocks` are used. Below are examples where the `query` field is omitted, and all bits from the targeted registry should be resolved:

#### Example 1: `blocks` in a Target
```yaml
targets:
- name: target
  template: ./template.tex.j2
  dest: ./out.pdf
  context:
    blocks:
      - registry: ./collection.yml
```

#### Example 2: Nested `blocks` Within a Block
```yaml
targets:
- name: target
  template: ./template.tex.j2
  dest: ./out.pdf
  context:
    blocks:
    - registry: ./collection.yml
      query:
        name: Equazioni
      context:
        blocks:
        - registry: ./collection.yml
```

#### Example 3: `blocks` in Bit Defaults
```yaml
bits:
- name: Equazioni
  tags: [equazioni]
  defaults:
    blocks:
    - registry: ./collection.yml
  src: |
    Risolvi le seguenti equazioni.
    
    \BLOCK{ if blocks|length > 0 }
    \begin{enumerate}
    \BLOCK{ for block in blocks }
    \item \VAR{ block.render() }
    \BLOCK{ endfor }
    \end{enumerate}
    \BLOCK{ endif }
```

### Expected Behavior
In each of these examples, a `blocks` entry containing a `registry` but no `query` field should automatically resolve to include all bits from the specified `registry` (e.g., `./collection.yml`).

This enhancement ensures flexibility and consistency in cases where no specific filtering criteria (`query`) are provided.
